# Generated by Django 5.1.6 on 2025-02-22 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
    ]
